### ISSUE TITLE
Composer install error

### ISSUE THREAD

**Issue by ugintl** [arnaudom/ek_template#1]
When I run composer `create-project` command, it gives `could not find package` error. So I downloaded the repository and then inside it run `composer install`. It went well, but when I run `composer update`, it gives error ```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - arreasystems/ek_profile dev-master requires fullcalendar/fullcalendar 3.10.2 -> satisfiable by fullcalendar/fullcalendar[v3.10.2] but these conflict with your requirements or minimum-stability.
    - arreasystems/ek_profile dev-master requires fullcalendar/fullcalendar 3.10.2 -> satisfiable by fullcalendar/fullcalendar[v3.10.2] but these conflict with your requirements or minimum-stability.
    - Installation request for arreasystems/ek_profile dev-master -> satisfiable by arreasystems/ek_profile[dev-master].
```

It is still using drupal 8.8, so I wanted to update it.

**Comment by ugintl** [comment]
I still tried to install it and got following error

![ek-template](https://user-images.githubusercontent.com/12570802/128629847-f5fa34a0-bb8f-451d-8f8d-f898b6848385.jpeg)

**Comment by arnaudom** [comment]
"failed to open settings.php"

You probably have a server configuration that prevent it to edit the file or the file edit permissions are not set for editing by the server. settings.php should be editable.

**Comment by ugintl** [comment]
Are you talking about composer update or site installation? I frequently install sites. If there is permission issue, then other sites must also have this issue. I am on windows. Using laragon software. It is a software like xampp, wamp etc etc.

**Comment by ugintl** [comment]
You were right. I made the default/sites folder writable and installation proceeded and finished, but I still see the error in red you see in above screenshot. Once the site was installed, it took me through different steps like ek_sales/install, ek_products/install and other steps. 

All worked fine, but When I reach ek_projects/install and ek_finance/install, it gave me `Website encountered an unexpected error` and now I cannot access front of my site.. I cannot access ek_admin.

**I can still access admin panel though. Below error is from the logs**

`Notice: Trying to access array offset on value of type null in Drupal\Component\Annotation\Doctrine\DocParser->Identifier() (line 969 of C:\laragon\www\ek_template\web\core\lib\Drupal\Component\Annotation\Doctrine\DocParser.php) #0 C:\laragon\www\ek_template\web\core\includes\bootstrap.inc(596): _drupal_error_handler_real(8, 'Trying to acces...', 'C:\\laragon\\www\\...', 969, Array) #1 C:\laragon\www\ek_template\web\core\lib\Drupal\Component\Annotation\Doctrine\DocParser.php(969): _drupal_error_handler(8, 'Trying to acces...', 'C:\\laragon\\www\\...', 969, Array) #2 C:\laragon\www\ek_template\web\core\lib\Drupal\Component\Annotation\Doctrine\DocParser.php(664): Drupal\Component\Annotation\Doctrine\DocParser->Identifier() #3 C:\laragon\www\ek_template\web\core\lib\Drupal\Component\Annotation\Doctrine\DocParser.php(640): Drupal\Component\Annotation\Doctrine\DocParser->Annotation() #4 C:\laragon\www\ek_template\web\core\lib\Drupal\Component\Annotation\Doctrine\DocParser.php(338): Drupal\Component\Annotation\Doctrine\DocParser->Annotations() #5 C:\laragon\www\ek_template\web\core\lib\Drupal\Component\Annotation\Doctrine\DocParser.php(495): Drupal\Component\Annotation\Doctrine\DocParser->parse('/**\n * Defines ...', 'class @Drupal\\v...') #6 C:\laragon\www\ek_template\web\core\lib\Drupal\Component\Annotation\Doctrine\DocParser.php(720): Drupal\Component\Annotation\Doctrine\DocParser->collectAnnotationMetadata('Drupal\\views\\An...') #7 C:\laragon\www\ek_template\web\core\lib\Drupal\Component\Annotation\Doctrine\DocParser.php(640): Drupal\Component\Annotation\Doctrine\DocParser->Annotation() #8 C:\laragon\www\ek_template\web\core\lib\Drupal\Component\Annotation\Doctrine\DocParser.php(338): Drupal\Component\Annotation\Doctrine\DocParser->Annotations() #9 C:\laragon\www\ek_template\web\core\lib\Drupal\Component\Annotation\Doctrine\SimpleAnnotationReader.php(101): Drupal\Component\Annotation\Doctrine\DocParser->parse('/**\n * Caching ...', 'class Drupal\\vi...') #10 C:\laragon\www\ek_template\web\core\lib\Drupal\Component\Annotation\Doctrine\SimpleAnnotationReader.php(125): Drupal\Component\Annotation\Doctrine\SimpleAnnotationReader->getClassAnnotations(Object(Doctrine\Common\Reflection\StaticReflectionClass)) #11 C:\laragon\www\ek_template\web\core\lib\Drupal\Component\Annotation\Plugin\Discovery\AnnotatedClassDiscovery.php(145): Drupal\Component\Annotation\Doctrine\SimpleAnnotationReader->getClassAnnotation(Object(Doctrine\Common\Reflection\StaticReflectionClass), 'Drupal\\views\\An...') #12 C:\laragon\www\ek_template\web\core\lib\Drupal\Component\Plugin\Discovery\DerivativeDiscoveryDecorator.php(86): Drupal\Component\Annotation\Plugin\Discovery\AnnotatedClassDiscovery->getDefinitions() #13 C:\laragon\www\ek_template\web\core\lib\Drupal\Core\Plugin\DefaultPluginManager.php(284): Drupal\Component\Plugin\Discovery\DerivativeDiscoveryDecorator->getDefinitions() #14 C:\laragon\www\ek_template\web\core\lib\Drupal\Core\Plugin\DefaultPluginManager.php(175): Drupal\Core\Plugin\DefaultPluginManager->findDefinitions() #15 C:\laragon\www\ek_template\web\core\lib\Drupal\Component\Plugin\Discovery\DiscoveryCachedTrait.php(22): Drupal\Core\Plugin\DefaultPluginManager->getDefinitions() #16 C:\laragon\www\ek_template\web\core\lib\Drupal\Core\Plugin\Factory\ContainerFactory.php(16): Drupal\Core\Plugin\DefaultPluginManager->getDefinition('none') #17 C:\laragon\www\ek_template\web\core\lib\Drupal\Component\Plugin\PluginManagerBase.php(83): Drupal\Core\Plugin\Factory\ContainerFactory->createInstance('none', Array) #18 C:\laragon\www\ek_template\web\core\modules\views\src\Plugin\views\display\DisplayPluginBase.php(819): Drupal\Component\Plugin\PluginManagerBase->createInstance('none') #19 C:\laragon\www\ek_template\web\core\modules\views\src\ViewExecutable.php(1416): Drupal\views\Plugin\views\display\DisplayPluginBase->getPlugin('cache') #20 C:\laragon\www\ek_template\web\core\modules\views\src\ViewExecutable.php(1454): Drupal\views\ViewExecutable->execute(NULL) #21 C:\laragon\www\ek_template\web\core\modules\views\src\Plugin\views\display\Page.php(183): Drupal\views\ViewExecutable->render() #22 C:\laragon\www\ek_template\web\core\modules\views\src\ViewExecutable.php(1630): Drupal\views\Plugin\views\display\Page->execute() #23 C:\laragon\www\ek_template\web\core\modules\views\src\Element\View.php(77): Drupal\views\ViewExecutable->executeDisplay('page', Array) #24 [internal function]: Drupal\views\Element\View::preRenderViewElement(Array) #25 C:\laragon\www\ek_template\web\core\lib\Drupal\Core\Security\DoTrustedCallbackTrait.php(100): call_user_func_array(Array, Array) #26 C:\laragon\www\ek_template\web\core\lib\Drupal\Core\Render\Renderer.php(781): Drupal\Core\Render\Renderer->doTrustedCallback(Array, Array, 'Render #pre_ren...', 'silenced_deprec...', 'Drupal\\Core\\Ren...') #27 C:\laragon\www\ek_template\web\core\lib\Drupal\Core\Render\Renderer.php(372): Drupal\Core\Render\Renderer->doCallback('#pre_render', Array, Array) #28 C:\laragon\www\ek_template\web\core\lib\Drupal\Core\Render\Renderer.php(200): Drupal\Core\Render\Renderer->doRender(Array, false) #29 C:\laragon\www\ek_template\web\core\lib\Drupal\Core\Render\MainContent\HtmlRenderer.php(226): Drupal\Core\Render\Renderer->render(Array, false) #30 C:\laragon\www\ek_template\web\core\lib\Drupal\Core\Render\Renderer.php(573): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() #31 C:\laragon\www\ek_template\web\core\lib\Drupal\Core\Render\MainContent\HtmlRenderer.php(227): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #32 C:\laragon\www\ek_template\web\core\lib\Drupal\Core\Render\MainContent\HtmlRenderer.php(117): Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch)) #33 C:\laragon\www\ek_template\web\core\lib\Drupal\Core\EventSubscriber\MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch)) #34 [internal function]: Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher)) #35 C:\laragon\www\ek_template\web\core\lib\Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher)) #36 C:\laragon\www\ek_template\vendor\symfony\http-kernel\HttpKernel.php(156): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent)) #37 C:\laragon\www\ek_template\vendor\symfony\http-kernel\HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #38 C:\laragon\www\ek_template\web\core\lib\Drupal\Core\StackMiddleware\Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #39 C:\laragon\www\ek_template\web\core\lib\Drupal\Core\StackMiddleware\KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #40 C:\laragon\www\ek_template\web\core\modules\page_cache\src\StackMiddleware\PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #41 C:\laragon\www\ek_template\web\core\modules\page_cache\src\StackMiddleware\PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #42 C:\laragon\www\ek_template\web\core\lib\Drupal\Core\StackMiddleware\ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #43 C:\laragon\www\ek_template\web\core\lib\Drupal\Core\StackMiddleware\NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #44 C:\laragon\www\ek_template\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #45 C:\laragon\www\ek_template\web\core\lib\Drupal\Core\DrupalKernel.php(694): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #46 C:\laragon\www\ek_template\web\index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #47 {main}.`

**Comment by arnaudom** [comment]
I need to test again the modules installation.
The above log is a "Notice:", not an error and it does not show any of the application modules.
There should be specific error log from module or DB if you have a "Website encountered an unexpected error".

**Comment by arnaudom** [comment]
I have update the template and profile for Drupal 9 compatibility.
You should be able to install with composer and latest Drupal 9 version:

`composer create-project arreasystems/ek_template:dev-master DIRECTORY --no-interaction`

You can also download the template and run:

`composer install`

 Tested several times, but may still have errors. Please report if any.

**Comment by ugintl** [comment]
`create-project` command went well. I used composer 2 this time. At the end I see this

```
Class DrupalComposer\DrupalScaffold\Plugin is not autoloadable, can not call post-update-cmd script
Class DrupalProject\composer\ScriptHandler is not autoloadable, can not call post-update-cmd script
```

From another D9 project, I copied the scripts folder from the root. I thought may be it will solve the problem, but still showing.

**Comment by ugintl** [comment]
Site installed perfectly. Everything looks good. Why does it ask for database details after site is installed? Currently I am developing locally. If I upload the site to a hosting, where to edit the database details? The database details provides during install and after the site is installed, are both different?

**Comment by arnaudom** [comment]
The application splits the data in 2 databases. You can have application settings and corporate data separated or remotely stored (ie. [https://arrea-systems.com/news_files_storage](url) )
This is also easier when updating Drupal, you don't worry about company data.

**Comment by ugintl** [comment]
Where is the second db details saved?

**Comment by ugintl** [comment]
How to generate demo data?

**Comment by arnaudom** [comment]
there is no solution for that right now.

**Comment by arnaudom** [comment]
> Where is the second db details saved?

same database service of Drupal or any other database service you wish. This is just an option to split the data.
Connection details are in settings.php.

**Comment by ugintl** [comment]
ok thanks. I checked the db logs and I am seeing these 2 errors. I think it has something to do with finance module

**Error1**

```
Notice: Array to string conversion in Drupal\Core\Menu\DefaultMenuLinkTreeManipulators->generateIndexAndSort() (line 236 of C:\laragon\www\erp\html\core\lib\Drupal\Core\Menu\DefaultMenuLinkTreeManipulators.php)

#0 C:\laragon\www\erp\html\core\includes\bootstrap.inc(312): _drupal_error_handler_real(8, 'Array to string...', 'C:\\laragon\\www\\...', 236)
#1 C:\laragon\www\erp\html\core\lib\Drupal\Core\Menu\DefaultMenuLinkTreeManipulators.php(236): _drupal_error_handler(8, 'Array to string...', 'C:\\laragon\\www\\...', 236, Array)
#2 [internal function]: Drupal\Core\Menu\DefaultMenuLinkTreeManipulators->generateIndexAndSort(Array)
#3 C:\laragon\www\erp\html\core\lib\Drupal\Core\Menu\MenuLinkTree.php(149): call_user_func(Array, Array)
#4 C:\laragon\www\erp\html\core\modules\system\src\Plugin\Block\SystemMenuBlock.php(193): Drupal\Core\Menu\MenuLinkTree->transform(Array, Array)
#5 C:\laragon\www\erp\html\core\modules\block\src\BlockViewBuilder.php(171): Drupal\system\Plugin\Block\SystemMenuBlock->build()
#6 [internal function]: Drupal\block\BlockViewBuilder::preRender(Array)
#7 C:\laragon\www\erp\html\core\lib\Drupal\Core\Security\DoTrustedCallbackTrait.php(101): call_user_func_array(Array, Array)
#8 C:\laragon\www\erp\html\core\lib\Drupal\Core\Render\Renderer.php(786): Drupal\Core\Render\Renderer->doTrustedCallback(Array, Array, 'Render #pre_ren...', 'exception', 'Drupal\\Core\\Ren...')
#9 C:\laragon\www\erp\html\core\lib\Drupal\Core\Render\Renderer.php(377): Drupal\Core\Render\Renderer->doCallback('#pre_render', Array, Array)
#10 C:\laragon\www\erp\html\core\lib\Drupal\Core\Render\Renderer.php(449): Drupal\Core\Render\Renderer->doRender(Array)
#11 C:\laragon\www\erp\html\core\lib\Drupal\Core\Render\Renderer.php(201): Drupal\Core\Render\Renderer->doRender(Array, false)
#12 C:\laragon\www\erp\html\core\lib\Drupal\Core\Template\TwigExtension.php(450): Drupal\Core\Render\Renderer->render(Array)
#13 C:\laragon\www\erp\html\sites\default\files\php\twig\6111312e1a47b_page.html.twig_FO9YmbWnAvAvZiQGMExqiOPLe\XMPq0kfNidu7gUf0o82QfOkf8gqiIDVyRDK2jPSVmRE.php(109): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#14 C:\laragon\www\erp\vendor\twig\twig\src\Template.php(405): __TwigTemplate_c3fc217acbc977951832b127d022a3b3683b3574d81296c8199bf636f378e325->doDisplay(Array, Array)
#15 C:\laragon\www\erp\vendor\twig\twig\src\Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#16 C:\laragon\www\erp\vendor\twig\twig\src\Template.php(390): Twig\Template->display(Array)
#17 C:\laragon\www\erp\html\core\themes\engines\twig\twig.engine(65): Twig\Template->render(Array)
#18 C:\laragon\www\erp\html\core\lib\Drupal\Core\Theme\ThemeManager.php(384): twig_render_template('core/themes/bar...', Array)
#19 C:\laragon\www\erp\html\core\lib\Drupal\Core\Render\Renderer.php(436): Drupal\Core\Theme\ThemeManager->render('page', Array)
#20 C:\laragon\www\erp\html\core\lib\Drupal\Core\Render\Renderer.php(201): Drupal\Core\Render\Renderer->doRender(Array, false)
#21 C:\laragon\www\erp\html\core\lib\Drupal\Core\Template\TwigExtension.php(450): Drupal\Core\Render\Renderer->render(Array)
#22 C:\laragon\www\erp\html\sites\default\files\php\twig\6111312e1a47b_html.html.twig_lxQmCTCPhmePpRynYoAljPqYE\fiMyR9FmZFr1jU69zA7pQnoKhcea2edYEljTUVN9MT4.php(86): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#23 C:\laragon\www\erp\vendor\twig\twig\src\Template.php(405): __TwigTemplate_3344b88350a8f79e49172ddb8a583de6d6ca843bf4e14a008ca5c76568ddce6d->doDisplay(Array, Array)
#24 C:\laragon\www\erp\vendor\twig\twig\src\Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#25 C:\laragon\www\erp\vendor\twig\twig\src\Template.php(390): Twig\Template->display(Array)
#26 C:\laragon\www\erp\html\core\themes\engines\twig\twig.engine(65): Twig\Template->render(Array)
#27 C:\laragon\www\erp\html\core\lib\Drupal\Core\Theme\ThemeManager.php(384): twig_render_template('core/themes/bar...', Array)
#28 C:\laragon\www\erp\html\core\lib\Drupal\Core\Render\Renderer.php(436): Drupal\Core\Theme\ThemeManager->render('html', Array)
#29 C:\laragon\www\erp\html\core\lib\Drupal\Core\Render\Renderer.php(201): Drupal\Core\Render\Renderer->doRender(Array, false)
#30 C:\laragon\www\erp\html\core\lib\Drupal\Core\Render\MainContent\HtmlRenderer.php(162): Drupal\Core\Render\Renderer->render(Array)
#31 C:\laragon\www\erp\html\core\lib\Drupal\Core\Render\Renderer.php(578): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}()
#32 C:\laragon\www\erp\html\core\lib\Drupal\Core\Render\MainContent\HtmlRenderer.php(163): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#33 C:\laragon\www\erp\html\core\lib\Drupal\Core\EventSubscriber\MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#34 [internal function]: Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#35 C:\laragon\www\erp\html\core\lib\Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher.php(142): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#36 C:\laragon\www\erp\vendor\symfony\http-kernel\HttpKernel.php(163): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view')
#37 C:\laragon\www\erp\vendor\symfony\http-kernel\HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#38 C:\laragon\www\erp\html\core\lib\Drupal\Core\StackMiddleware\Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#39 C:\laragon\www\erp\html\core\lib\Drupal\Core\StackMiddleware\KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#40 C:\laragon\www\erp\html\core\modules\page_cache\src\StackMiddleware\PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#41 C:\laragon\www\erp\html\core\modules\page_cache\src\StackMiddleware\PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#42 C:\laragon\www\erp\html\core\lib\Drupal\Core\StackMiddleware\ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#43 C:\laragon\www\erp\html\core\lib\Drupal\Core\StackMiddleware\NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#44 C:\laragon\www\erp\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#45 C:\laragon\www\erp\html\core\lib\Drupal\Core\DrupalKernel.php(717): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#46 C:\laragon\www\erp\html\index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#47 {main}
```

**Comment by ugintl** [comment]
**Error2**

```
Notice: Trying to access array offset on value of type bool in Drupal\ek_finance\FinanceSettings->get() (line 33 of C:\laragon\www\erp\html\modules\contrib\ek\ek_finance\src\FinanceSettings.php)

#0 C:\laragon\www\erp\html\core\includes\bootstrap.inc(312): _drupal_error_handler_real(8, 'Trying to acces...', 'C:\\laragon\\www\\...', 33)
#1 C:\laragon\www\erp\html\modules\contrib\ek\ek_finance\src\FinanceSettings.php(33): _drupal_error_handler(8, 'Trying to acces...', 'C:\\laragon\\www\\...', 33, Array)
#2 C:\laragon\www\erp\html\modules\contrib\ek\ek_finance\src\Form\FinanceSettingsForm.php(228): Drupal\ek_finance\FinanceSettings->get('listPurchases')
#3 [internal function]: Drupal\ek_finance\Form\FinanceSettingsForm->buildForm(Array, Object(Drupal\Core\Form\FormState))
#4 C:\laragon\www\erp\html\core\lib\Drupal\Core\Form\FormBuilder.php(532): call_user_func_array(Array, Array)
#5 C:\laragon\www\erp\html\core\lib\Drupal\Core\Form\FormBuilder.php(278): Drupal\Core\Form\FormBuilder->retrieveForm('ek_edit_finance...', Object(Drupal\Core\Form\FormState))
#6 C:\laragon\www\erp\html\core\lib\Drupal\Core\Form\FormBuilder.php(219): Drupal\Core\Form\FormBuilder->buildForm('Drupal\\ek_finan...', Object(Drupal\Core\Form\FormState))
#7 C:\laragon\www\erp\html\modules\contrib\ek\ek_finance\src\Controller\SettingsController.php(28): Drupal\Core\Form\FormBuilder->getForm('Drupal\\ek_finan...')
#8 [internal function]: Drupal\ek_finance\Controller\SettingsController->settings(Object(Symfony\Component\HttpFoundation\Request))
#9 C:\laragon\www\erp\html\core\lib\Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#10 C:\laragon\www\erp\html\core\lib\Drupal\Core\Render\Renderer.php(578): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#11 C:\laragon\www\erp\html\core\lib\Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#12 C:\laragon\www\erp\html\core\lib\Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#13 C:\laragon\www\erp\vendor\symfony\http-kernel\HttpKernel.php(158): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#14 C:\laragon\www\erp\vendor\symfony\http-kernel\HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#15 C:\laragon\www\erp\html\core\lib\Drupal\Core\StackMiddleware\Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 C:\laragon\www\erp\html\core\lib\Drupal\Core\StackMiddleware\KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 C:\laragon\www\erp\html\core\modules\page_cache\src\StackMiddleware\PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#18 C:\laragon\www\erp\html\core\modules\page_cache\src\StackMiddleware\PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#19 C:\laragon\www\erp\html\core\lib\Drupal\Core\StackMiddleware\ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#20 C:\laragon\www\erp\html\core\lib\Drupal\Core\StackMiddleware\NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#21 C:\laragon\www\erp\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#22 C:\laragon\www\erp\html\core\lib\Drupal\Core\DrupalKernel.php(717): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#23 C:\laragon\www\erp\html\index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#24 {main}
```

**Comment by arnaudom** [comment]
this is not an error, just a notice.
It is generated by the message tag in menu when you have an unread message.

**Comment by ugintl** [comment]
I have 2 questions.

1. I want to create content from the UI, but there are lot of things so I am confused where to start. Can you please tell me priority wise which content to create first?

2. Do you know of any contrib modules which will extend the functionality of ek? For example rules, charts etc etc. Tell me any you can think of. It is your module. You know it better than anyone?

**Comment by arnaudom** [comment]
Charts, mailsystem and swiftmailer are the only modules that interact with EK to some extend.
Many other modules can by used as for a normal drupal website depending on your need. We use s3fs, autologout, clamav, data_policy, permission_spreadsheet, for instance.
Check [https://arrea-systems.com/tutorial-setup](url) for basic start help.

**Comment by ugintl** [comment]
I am seeing this error on the front side of the website.

```
Deprecated: Array and string offset access syntax with curly braces is deprecated in C:\laragon\www\erp\vendor\tecnickcom\tcpdf\tcpdf.php on line 16900

Deprecated: Array and string offset access syntax with curly braces is deprecated in C:\laragon\www\erp\vendor\tecnickcom\tcpdf\tcpdf.php on line 16900

Deprecated: Array and string offset access syntax with curly braces is deprecated in C:\laragon\www\erp\vendor\tecnickcom\tcpdf\tcpdf.php on line 16903

Deprecated: Array and string offset access syntax with curly braces is deprecated in C:\laragon\www\erp\vendor\tecnickcom\tcpdf\include\tcpdf_images.php on line 314
```

**Comment by arnaudom** [comment]
you should then report issue to vendor tecnickcom/tcpdf

**Comment by ugintl** [comment]
Please change the tcpdf library version to 6.3 in ek_profile. I think it will solve the issue. It is a problem when using php 7.4

**Comment by ugintl** [comment]
I created a issue and they replied https://github.com/tecnickcom/TCPDF/issues/417
